### ISSUE TITLE
Conflict using @badeball/cypress-cucumber-preprocessor plugin with cypress-cloud config.

### ISSUE THREAD

**Issue by samixchoumi** [currents-dev/cypress-cloud#142]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>
```
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 623.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Firefox: 113.0.2
    Safari: 16.5
  npmPackages:
    @badeball/cypress-cucumber-preprocessor: ^17.2.0 => 17.2.0 
    @bahmutov/cypress-esbuild-preprocessor: ^2.2.0 => 2.2.0 
    @cypress/angular:  0.0.0-development 
    @cypress/mount-utils:  0.0.0-development 
    @cypress/react:  0.0.0-development 
    @cypress/react18:  0.0.0-development 
    @cypress/svelte:  0.0.0-development 
    @cypress/vue:  0.0.0-development 
    @cypress/vue2:  0.0.0-development 
    @shelex/cypress-allure-plugin: ^2.39.1 => 2.39.1 
    @typescript-eslint/eslint-plugin: ^5.59.7 => 5.59.8 
    @typescript-eslint/parser: ^5.59.7 => 5.59.8 
    allure-js-commons: ^2.3.0 => 2.4.0 
    cy2: ^4.0.6 => 4.0.6 (3.4.3)
    cypress: ^12.13.0 => 12.13.0 
    cypress-cloud: ^1.7.4 => 1.7.4 
    cypress-multi-reporters: ^1.6.3 => 1.6.3 
    cypress-real-events: ^1.8.1 => 1.8.1 
    cypress-recurse: ^1.35.1 => 1.35.2 
    cypress-slack-reporter: ^1.5.3 => 1.5.3 
    cypress-slow-down: ^1.2.1 => 1.2.1 
    cypress-time-marks: ^1.4.0 => 1.4.0 
    esbuild: ^0.17.19 => 0.17.19 (0.14.54)
    eslint: ^8.41.0 => 8.41.0 
    eslint-plugin-cypress: ^2.13.3 => 2.13.3 
    fs-extra: ^11.1.1 => 11.1.1 (9.1.0, 7.0.1, 10.1.0)
    mocha: ^10.2.0 => 10.2.0 
    mochawesome: ^7.1.3 => 7.1.3 
    mochawesome-merge: ^4.3.0 => 4.3.0 
    mochawesome-report-generator: ^6.2.0 => 6.2.0 
    moment: ^2.29.4 => 2.29.4 
    typescript: ^5.0.4 => 5.0.4 
    uid: ^2.0.2 => 2.0.2 
  npmGlobalPackages:
    corepack: 0.14.2
    npm: 9.6.4
```
</details>

### Describe the bug

When launching `CURRENTS_PROJECT_ID=xxx npx cypress-cloud run --record --key XXX --parallel --ci-build-id $CI_PIPELINE_ID --env allure=true,configFile=dev --browser chrome`, I got that error : 

```
2023-06-13T13:21:03.626Z cypress:lifecycle:child:RunPlugins:51428 plugins file errored: TypeError: cloudPlugin is not a function
    at file:///Users/samueldubernet/IdeaProjects/sbc-e2e-tests/cypress.config.ts:66:10
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/samueldubernet/IdeaProjects/sbc-e2e-tests/cypress.config.ts:4:58)
```

### Expected behavior

No error, tests working fine.

### Command and Setup

Command : 
`CURRENTS_PROJECT_ID=xxx npx cypress-cloud run --record --key XXX --parallel --ci-build-id $CI_PIPELINE_ID --env allure=true,configFile=dev --browser chrome`

Setup - currents.config.js : 
```
// currents.config.js
module.exports = {
  projectId: "yyy",
  recordKey: "xxx",
  // Sorry Cypress users - set the director service URL
  cloudServiceUrl: "http://10.3.8.6:1234/",
};
```

Setup - cypress.config.ts : 
```
import { defineConfig } from 'cypress';
import cloudPlugin from 'cypress-cloud/plugin';
import createBundler from '@bahmutov/cypress-esbuild-preprocessor';
import preprocessor from '@badeball/cypress-cucumber-preprocessor';
import { createEsbuildPlugin } from '@badeball/cypress-cucumber-preprocessor/esbuild';
import allureWriter from '@shelex/cypress-allure-plugin/writer';

async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config);
  on(
    'file:preprocessor',
    createBundler({
      plugins: [createEsbuildPlugin(config)]
    })
  );
  allureWriter(on, config);
  // Make sure to return the config object as it might have been modified by the plugin.
  return cloudPlugin(on, config);
}

export default defineConfig({
  //Cypress run parameters
  chromeWebSecurity: false,
  includeShadowDom: true,
  video: false,
  reporter: 'cypress-multi-reporters',
  experimentalMemoryManagement: true,
  numTestsKeptInMemory: 0,
  reporterOptions: {
    configFile: 'reporterOpts.json'
  },
  e2e: {
    specPattern: ['./cypress/integration/**/*.feature'],
    excludeSpecPattern: './cypress/integration/Not implemented yet',
    defaultCommandTimeout: 20000,
    requestTimeout: 20000,
    setupNodeEvents,
    baseUrl: 'https://localhost.com',
    env: {
      jsonEnabled: true,
      jsonOutput: './cypress/cucumber-json/cucumber-json.json',
      allureReuseAfterSpec: true,
      allureOmitPreviousAttemptScreenshots: false,
      environment: 'dev',
    }
  },
  retries: {
    runMode: 0,
    openMode: 0
  }
});
```

Setup - package.json : 
```
{
  "name": "projectName",
  "version": "1.0.0",
  "description": "Project to make automation test",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "CURRENTS_PROJECT_ID=xxx npx cypress-cloud run --record --key XXX --parallel --ci-build-id $CI_PIPELINE_ID --env allure=true,configFile=dev --browser chrome",
    "test:debug": "CURRENTS_PROJECT_ID=xxx DEBUG=currents:*,cypress:* npx cypress-cloud run --record --key XXX --parallel --ci-build-id $CI_PIPELINE_ID --env allure=true,configFile=dev --browser chrome",
  },
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^17.2.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",
    "@shelex/cypress-allure-plugin": "^2.39.1",
    "@typescript-eslint/eslint-plugin": "^5.59.7",
    "@typescript-eslint/parser": "^5.59.7",
    "allure-js-commons": "^2.3.0",
    "cy2": "^4.0.6",
    "cypress": "^12.13.0",
    "cypress-cloud": "^1.7.4",
    "cypress-multi-reporters": "^1.6.3",
    "cypress-real-events": "^1.8.1",
    "cypress-recurse": "^1.35.1",
    "cypress-slack-reporter": "^1.5.3",
    "cypress-slow-down": "^1.2.1",
    "cypress-time-marks": "^1.4.0",
    "esbuild": "^0.17.19",
    "eslint": "^8.41.0",
    "eslint-plugin-cypress": "^2.13.3",
    "fs-extra": "^11.1.1",
    "mocha": "^10.2.0",
    "mochawesome": "^7.1.3",
    "mochawesome-merge": "^4.3.0",
    "mochawesome-report-generator": "^6.2.0",
    "moment": "^2.29.4",
    "typescript": "^5.0.4"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "uid": "^2.0.2"
  }
}
```

### Full log and debug output

<details>
```
2023-06-13T13:21:03.606Z cypress:lifecycle:child:RunPlugins:51428 Loading the RunPlugins
2023-06-13T13:21:03.606Z cypress:lifecycle:child:RunPlugins:51428 register event _get:task:body with id 0
2023-06-13T13:21:03.606Z cypress:lifecycle:child:RunPlugins:51428 register event _get:task:keys with id 1
2023-06-13T13:21:03.606Z cypress:lifecycle:child:RunPlugins:51428 register event _process:cross:origin:callback with id 2
2023-06-13T13:21:03.606Z cypress:lifecycle:child:RunPlugins:51428 Calling setupNodeEvents
2023-06-13T13:21:03.623Z cypress:lifecycle:child:RunPlugins:51428 register event before:run with id 3
2023-06-13T13:21:03.624Z cypress:lifecycle:child:RunPlugins:51428 register event after:run with id 4
2023-06-13T13:21:03.624Z cypress:lifecycle:child:RunPlugins:51428 register event before:spec with id 5
2023-06-13T13:21:03.624Z cypress:lifecycle:child:RunPlugins:51428 register event after:spec with id 6
2023-06-13T13:21:03.624Z cypress:lifecycle:child:RunPlugins:51428 register event after:screenshot with id 7
2023-06-13T13:21:03.624Z cypress:lifecycle:child:RunPlugins:51428 register event task with id 8
2023-06-13T13:21:03.624Z cypress:lifecycle:child:RunPlugins:51428 register event file:preprocessor with id 9
2023-06-13T13:21:03.624Z cypress:lifecycle:child:RunPlugins:51428 extend task events with id 8
2023-06-13T13:21:03.624Z cypress:lifecycle:child:RunPlugins:51428 register event before:browser:launch with id 10
2023-06-13T13:21:03.624Z cypress:lifecycle:child:RunPlugins:51428 extend task events with id 8
2023-06-13T13:21:03.626Z cypress:lifecycle:child:RunPlugins:51428 plugins file errored: TypeError: cloudPlugin is not a function
    at file:///Users/username/IdeaProjects/projectName/cypress.config.ts:22:10
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/username/IdeaProjects/projectName/cypress.config.ts:4:58)
2023-06-13T13:21:03.642Z cypress:server:browsers browsers.kill called with no active instance
2023-06-13T13:21:03.661Z cypress:cli child event fired { event: 'exit', code: 1, signal: null }
 ERROR  Unable to resolve cypress configuration
- make sure that 'cypress-cloud/plugin' is installed
- report the issue together with cypress stdout and stderr
```
</details>

**Comment by agoldis** [comment]
@samixchoumi here's an example output from 1.8.0-beta.5

`DEBUG=currents:* CURRENTS_API_URL=http://localhost:1234/ yarn cypress-cloud run --parallel --record --key Fgt2j7QCjNedC2zG --ci-build-id xxx`

Please try rerunning with the new version 

```
  currents:capture capturing stdout +0ms
  currents:cli parsed CLI flags { component: false, e2e: true, parallel: true, record: true, headed: false, key: 'Fgt2j7QCjNedC2zG', ciBuildId: '1686734062' } +0ms
  currents:cli parsed run params: { parallel: true, record: true, headed: false, key: 'Fgt2j7QCjNedC2zG', ciBuildId: '1686734062', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'Fgt2j7QCjNedC2zG' } +1ms
  currents:run run params { parallel: true, record: true, headed: false, key: 'Fgt2j7QCjNedC2zG', ciBuildId: '1686734062', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'Fgt2j7QCjNedC2zG' } +0ms
  currents:run params after preprocess { parallel: true, record: true, headed: false, key: 'Fgt2j7QCjNedC2zG', ciBuildId: '1686734062', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'Fgt2j7QCjNedC2zG', spec: undefined } +0ms
  currents:config loading currents config file from '/Users/agoldis/cypress-cloud/e2e/config-noesm-js/currents.config.js' +0ms
  currents:config loaded currents config from '/Users/agoldis/cypress-cloud/e2e/config-noesm-js/currents.config.js'
  currents:config {
  currents:config   e2e: { batchSize: 3 },
  currents:config   component: { batchSize: 5 },
  currents:config   projectId: 'l4zuz8'
  currents:config } +9ms
  currents:validateParams resolving currents params: { parallel: true, record: true, headed: false, key: 'Fgt2j7QCjNedC2zG', ciBuildId: '1686734062', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'Fgt2j7QCjNedC2zG', spec: undefined } +0ms
  currents:validateParams resolving currents config file: { e2e: { batchSize: 3 }, component: { batchSize: 5 }, projectId: 'l4zuz8' } +0ms
  currents:validateParams validating currents params: { parallel: true, record: true, headed: false, key: 'Fgt2j7QCjNedC2zG', ciBuildId: '1686734062', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'Fgt2j7QCjNedC2zG', spec: undefined, cloudServiceUrl: 'http://localhost:1234/', projectId: 'l4zuz8', batchSize: 3 } +0ms
  currents:validateParams validated currents params: { parallel: true, record: true, headed: false, key: 'Fgt2j7QCjNedC2zG', ciBuildId: '1686734062', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'Fgt2j7QCjNedC2zG', spec: undefined, cloudServiceUrl: 'http://localhost:1234/', projectId: 'l4zuz8', batchSize: 3, tag: [], autoCancelAfterFailures: undefined } +0ms
  currents:config resolving cypress config +0ms
  currents:boot booting cypress... +0ms
```

**Comment by samixchoumi** [comment]
Thanks @agoldis for your answer.
I updated the version to the beta and added `CURRENTS_API_URL` to my command (because it seem that the `currents.config.js` file doesn't work for me as you can see below.
My command looks like that now : `CURRENTS_PROJECT_ID=xxx CURRENTS_RECORD_KEY=yyy CURRENTS_API_URL=https://10.3.8.6:1234/ DEBUG=currents:*,cypress:* npx cypress-cloud run --record --key yyy --parallel --ci-build-id $CI_PIPELINE_ID --env allure=true,configFile=dev --browser chrome`

What I got now by adding the currents api url on the CLI is that : 

```
currents:capture capturing stdout +0ms
  cypress:cli exporting Cypress module interface +0ms
  currents:cli parsed CLI flags { component: false, e2e: true, parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome' } +0ms
  currents:cli parsed run params: { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy' } +1ms
  currents:run run params { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy' } +0ms
  currents:run params after preprocess { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy', spec: undefined } +0ms
  currents:config loading currents config file from '/Users/samixchoumi/IdeaProjects/projectName/currents.config.js' +0ms
  currents:config failed loading config file from: ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/samixchoumi/IdeaProjects/projectName/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/samixchoumi/IdeaProjects/projectName/currents.config.js:2:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at loadConfigFile (/Users/samixchoumi/IdeaProjects/projectName/node_modules/lib/config/config.ts:69:22)
    at getCurrentsConfig (/Users/samixchoumi/IdeaProjects/projectName/node_modules/lib/config/config.ts:46:26)
    at resolveCurrentsParams (/Users/samixchoumi/IdeaProjects/projectName/node_modules/lib/config/params.ts:16:26)
    at validateParams (/Users/samixchoumi/IdeaProjects/projectName/node_modules/lib/config/params.ts:76:18)
    at run (/Users/samixchoumi/IdeaProjects/projectName/node_modules/lib/run.ts:47:27) +4ms
  currents:config loading currents config file from '/Users/samixchoumi/IdeaProjects/projectName/currents.config.cjs' +19ms
  currents:config failed loading config file from: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/samixchoumi/IdeaProjects/projectName/currents.config.cjs' imported from /Users/samixchoumi/IdeaProjects/projectName/node_modules/cypress-cloud/bin/cli.js +0ms
  currents:config loading currents config file from '/Users/samixchoumi/IdeaProjects/projectName/currents.config.mjs' +0ms
  currents:config failed loading config file from: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/samixchoumi/IdeaProjects/projectName/currents.config.mjs' imported from /Users/samixchoumi/IdeaProjects/projectName/node_modules/cypress-cloud/bin/cli.js +1ms
 WARNING  Failed to load config file, falling back to the default config. Attempted locations: [
  '/Users/samixchoumi/IdeaProjects/projectName/currents.config.js',
  '/Users/samixchoumi/IdeaProjects/projectName/currents.config.cjs',
  '/Users/samixchoumi/IdeaProjects/projectName/currents.config.mjs'
]
  currents:validateParams resolving currents params: { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy', spec: undefined } +0ms
  currents:validateParams resolving currents config file: { e2e: { batchSize: 3 }, component: { batchSize: 5 }, cloudServiceUrl: 'https://cy.currents.dev' } +0ms
  currents:validateParams validating currents params: { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy', spec: undefined, cloudServiceUrl: 'https://10.3.8.6:1234/', projectId: 'xxx', batchSize: 3 } +0ms
  currents:validateParams validated currents params: { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy', spec: undefined, cloudServiceUrl: 'https://10.3.8.6:1234/', projectId: 'xxx', batchSize: 3, tag: [], autoCancelAfterFailures: undefined } +1ms
  currents:config resolving cypress config +2ms
  currents:boot booting cypress... +0ms
...
[lot of line]
...
Discovered 1 spec files
Tags: false; Group: false; Parallel: true; Batch Size: 3
Connecting to cloud orchestration service...
  currents:ci detected CI provider: null +0ms
  currents:ci detected CI params: {} +0ms
  currents:ci git commit existing info +30ms
  currents:ci {
  currents:ci   branch: 'feature/update_sorry_cypress_to_cypress-cloud',
  currents:ci   remoteOrigin: 'git@gitlab.com:project/qat/projectName.git',
  currents:ci   authorEmail: 'samixchoumi@mail.com',
  currents:ci   authorName: 'samixchoumi',
  currents:ci   message: 'Update cypress-cloud config\n',
  currents:ci   sha: '73ca7974b08a93953bd176668f49e7bb303c30da'
  currents:ci } +0ms
  currents:ci commit info from provider environment variables: {} +0ms
  currents:ci combined git and environment variables from provider +0ms
  currents:ci {
  currents:ci   branch: 'feature/update_sorry_cypress_to_cypress-cloud',
  currents:ci   remoteOrigin: 'git@gitlab.com:project/qat/projectName.git',
  currents:ci   authorEmail: 'samixchoumi@mail.com',
  currents:ci   authorName: 'samixchoumi',
  currents:ci   message: 'Update cypress-cloud config\n',
  currents:ci   sha: '73ca7974b08a93953bd176668f49e7bb303c30da'
  currents:ci } +0ms
  currents:api network request: { method: 'post', url: '/runs', headers: { Accept: 'application/json, text/plain, */*', 'Content-Type': 'application/json', 'x-cypress-request-attempt': 0, 'x-cypress-version': '12.13.0', 'x-ccy-version': '1.8.0-beta.5' }, data: { ci: { params: {}, provider: null }, specs: [ 'cypress/integration/Spec/AScenario.feature' ], commit: { branch: 'feature/update_sorry_cypress_to_cypress-cloud', remoteOrigin: 'git@gitlab.com:project/qat/projectName.git', authorEmail: 'samixchoumi@mail.com', authorName: 'samixchoumi', message: 'Update cypress-cloud config\n', sha: '73ca7974b08a93953bd176668f49e7bb303c30da' }, group: undefined, platform: { osName: 'darwin', osVersion: '22.5.0', osCpus: [Array], osMemory: [Object], browserName: 'Chrome', browserVersion: '114.0.5735.106' }, parallel: true, ciBuildId: '--env', projectId: 'xxx', recordKey: 'yyy', specPattern: [ './cypress/integration/**/*.feature' ], tags: [], testingType: 'e2e', batchSize: 3, autoCancelAfterFailures: undefined } } +0ms
 ERROR  write EPROTO 009E35EB01000000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
```

**Comment by agoldis** [comment]
@samixchoumi 
You're using ESM, but the syntax of `currents.config.js` is CJS-like - e.g. the use of `module` keyword.

```
currents:config failed loading config file from: ReferenceError: **module** is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/samixchoumi/IdeaProjects/projectName/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
   ....
```


`cypress-cloud` will search for a configuration file at the project's root location (defined with `-P --project` CLI option) in the following order:

- `currents.config.js`
- `currents.config.cjs`
- `currents.config.mjs`
The configuration file will be read using [import()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) expression. 

Please make sure that the file is formatted according to ESM syntax.

**Comment by samixchoumi** [comment]
Hello @agoldis, hope you're fine.
So I updated it like that : 
```
export const projectId = 'yyy';
export const recordKey = 'xxx';
// Sorry Cypress users - set the director service URL
export const cloudServiceUrl = 'https://localhost:1234/';
```
(Maybe add this example for ESM syntax cases on the README ?)
It seem to work better but their is an error when booting : 
```
currents:capture capturing stdout +0ms
  cypress:cli exporting Cypress module interface +0ms
  currents:cli parsed CLI flags { component: false, e2e: true, parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome' } +0ms
  currents:cli parsed run params: { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy' } +1ms
  currents:run run params { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy' } +0ms
  currents:run params after preprocess { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy', spec: undefined } +0ms
  currents:config loading currents config file from '/Users/samixchoumi/IdeaProjects/projectName/currents.config.js' +0ms
  currents:config loaded currents config from '/Users/samixchoumi/IdeaProjects/projectName/currents.config.js'
  currents:config {
  currents:config   e2e: { batchSize: 3 },
  currents:config   component: { batchSize: 5 },
  currents:config   cloudServiceUrl: 'https://localhost:1234/',
  currents:config   projectId: 'yyy',
  currents:config   recordKey: 'xxx'
  currents:config } +3ms
  currents:validateParams resolving currents params: { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy', spec: undefined } +0ms
  currents:validateParams resolving currents config file: { e2e: { batchSize: 3 }, component: { batchSize: 5 }, cloudServiceUrl: 'https://localhost:1234/', projectId: 'yyy', recordKey: 'xxx' } +0ms
  currents:validateParams validating currents params: { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy', spec: undefined, cloudServiceUrl: 'https://localhost:1234/', projectId: 'yyy', batchSize: 3 } +0ms
  currents:validateParams validated currents params: { parallel: true, record: true, headed: false, key: 'yyy', ciBuildId: '--env', browser: 'chrome', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: 'yyy', spec: undefined, cloudServiceUrl: 'https://localhost:1234/', projectId: 'yyy', batchSize: 3, tag: [], autoCancelAfterFailures: undefined } +0ms
  currents:config resolving cypress config +1ms
  currents:boot booting cypress... +0ms
  currents:boot cypress executable location: /Users/samixchoumi/IdeaProjects/projectName/node_modules/cypress/bin/cypress +1ms
  currents:boot cypress bootstrap params: { browser: 'chrome', record: false, env: { currents_temp_file: '/var/folders/jx/0hb5g7z5519027xtjtdd7r2w0000gp/T/tmp-20114-7qhYYdbHtPQF', currents_debug_enabled: true } } +0ms
  currents:boot cypress bootstrap serialized params: [ '--browser', 'chrome', '--record', false, '--env', '{"currents_temp_file":"/var/folders/jx/0hb5g7z5519027xtjtdd7r2w0000gp/T/tmp-20114-7qhYYdbHtPQF","currents_debug_enabled":true}' ] +0ms
  currents:boot booting cypress with args: [ '--browser', 'chrome', '--record', false, '--env', '{"currents_temp_file":"/var/folders/jx/0hb5g7z5519027xtjtdd7r2w0000gp/T/tmp-20114-7qhYYdbHtPQF","currents_debug_enabled":true}', '--spec', 'iossipxjlm', '--e2e' ] +1ms
  currents:boot exec cypress failed (certain failures are expected): Error: Command failed with exit code 1: /Users/samixchoumi/IdeaProjects/projectName/node_modules/cypress/bin/cypress run --browser chrome --record false --env {"currents_temp_file":"/var/folders/jx/0hb5g7z5519027xtjtdd7r2w0000gp/T/tmp-20114-7qhYYdbHtPQF","currents_debug_enabled":true} --spec iossipxjlm --e2e 2023-06-15T09:12:55.878Z cypress:cli:cli cli starts with arguments
...
[some line]
```

And looking at the end of the line, i have that : 
```cypress:server:cypress exiting with err Error: Can't run because no spec files were found.  We searched for specs matching this glob pattern:  > /Users/samueldubernet/IdeaProjects/sbc-e2e-tests/iossipxjlm at H (<embedded>:4696:527392) at process.processTicksAndRejections (node:internal/process/task_queues:96:5) { isCypressErr: true, type: 'NO_SPECS_FOUND', details: undefined, messageMarkdown: "Can't run because `no spec files` were found.\n" + '\n' + 'We searched for specs matching this glob pattern:\n' + '\n' + '  > /Users/samueldubernet/IdeaProjects/sbc-e2e-tests/iossipxjlm', originalError: undefined, stackWithoutMessage: '    at H (<embedded>:4696:527392)\n' + '    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)' } 2023-06-15T09:12:57.638Z cypress:server:cypress calling exit 1 2023-06-15T09:12:57.638Z cypress:server:cypress about to exit with code 1 2023-06-15T09:12:57.639Z cypress:server:browsers browsers.kill called with no active instance 2023-06-15T09:12:57.639Z cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 0, proxyRequestsReceived: 0, immediatelyMatchedRequests: 0, unmatchedRequests: 0, unmatchedPreRequests: 0 } 2023-06-15T09:12:57.654Z cypress:cli child event fired { event: 'exit', code: 1, signal: null } [currents:plugin] currents plugin loaded [currents:plugin] dumping config to '/var/folders/jx/0hb5g7z5519027xtjtdd7r2w0000gp/T/tmp-20114-7qhYYdbHtPQF' [currents:plugin] config is availabe at '/var/folders/jx/0hb5g7z5519027xtjtdd7r2w0000gp/T/tmp-20114-7qhYYdbHtPQF' Can't run because no spec files were found.  We searched for specs matching this glob pattern:  > /Users/samueldubernet/IdeaProjects/sbc-e2e-tests/iossipxjlm at makeError (/Users/samueldubernet/IdeaProjects/sbc-e2e-tests/node_modules/cypress-cloud/node_modules/execa/lib/error.js:60:11) at handlePromise (/Users/samueldubernet/IdeaProjects/sbc-e2e-tests/node_modules/cypress-cloud/node_modules/execa/index.js:118:26)     at processTicksAndRejections (node:internal/process/task_queues:95:5) at execCypress (/Users/samueldubernet/IdeaProjects/sbc-e2e-tests/node_modules/lib/bootstrap/bootstrap.ts:54:5) at bootCypress (/Users/samueldubernet/IdeaProjects/sbc-e2e-tests/node_modules/lib/bootstrap/bootstrap.ts:24:30) at getMergedConfig (/Users/samueldubernet/IdeaProjects/sbc-e2e-tests/node_modules/lib/config/config.ts:94:19) at run (/Users/samueldubernet/IdeaProjects/sbc-e2e-tests/node_modules/lib/run.ts:62:18)`

**Comment by samixchoumi** [comment]
Found the error, changed the `export const cloudServiceUrl = 'https://localhost:1234/';` to `export const cloudServiceUrl = 'http://localhost:1234/';`
It seem to work properly !
