### ISSUE TITLE
"TypeError: Expected a finite number" after finishing a run

### ISSUE THREAD

**Issue by killergege** [currents-dev/cypress-cloud#187]
### Please confirm

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I will include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

Cypress:        13.3.0                                                                        
Browser:        Electron 114 (headless)                                                       
Node Version:   v16.20.1   

Package.json:
"cypress": "^13.3.0",
"cypress-cloud": "^1.9.6",

</details>

### Describe the bug

We migrated recently to cypress 13 & cypress-cloud without any major issue, but we were using the beta client (1.10.0-beta.5)

Now we are trying to upgrade to the most recent version of cypress-cloud 

When we run the tests in parallel (we have a currents.dev subscription), all of our runs end with the following error:

```
    √  All specs passed!                        04:37        2        2        -        -        -  


  Reporting results and artifacts in background...  


====================================================================================================


  Cloud Run Finished  

TypeError: Expected a finite number
    at prettyMS (C:\a\2\s\Front\node_modules\pretty-ms\index.js:10:9)
    at C:\a\2\s\Front\node_modules\lib\results\table.ts:25:10
    at Array.map (<anonymous>)
    at summaryTable (C:\a\2\s\Front\node_modules\lib\results\table.ts:22:23)
    at run (C:\a\2\s\Front\node_modules\lib\run.ts:147:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
##[error]Cmd.exe exited with code '1'.
##[section]Finishing: Run Cypress tests 
```

The run appear as successful in Current.Dev dashboards.

Our analysis indicates that the [prettyMS function](https://github.com/currents-dev/cypress-cloud/blob/cb07e50eb1467293d74d328aec7610053013141e/packages/cypress-cloud/lib/results/table.ts#L25) is receiving an `undefined `value.

### Expected behavior

The run succeeds and the command exits with code 0.

### Setup and Command

Command used (there is not much in the config file beside the project id and some folder paths)
`npx cypress-cloud run --config-file ./apps/****-e2e/cypress.config.pp.ts --cloud-config-file ./apps/****-e2e/currents.config.js --record --parallel --tag pp --ci-build-id ****`

### Full log and debug output

<details>
This only the bottom of the logs, which seems the most relevant : 

```
2023-10-10T13:26:46.372Z cypress:server:cypress about to exit with code 0
2023-10-10T13:26:46.374Z cypress:server:browsers browsers.kill called with no active instance
2023-10-10T13:26:46.374Z cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 940, proxyRequestsReceived: 654, immediatelyMatchedRequests: 165, unmatchedRequests: 0, unmatchedPreRequests: 53 }
2023-10-10T13:26:46.527Z cypress:cli child event fired { event: 'exit', code: 0, signal: null }
2023-10-10T13:26:46.527Z cypress:cli child event fired { event: 'close', code: 0, signal: null }
2023-10-10T13:26:46.529Z currents:cypress cypress run result { browserName: 'electron', browserPath: '', browserVersion: '114.0.5735.289', config: { configFile: '****', testingType: 'e2e', env: { }, baseUrl: '***', retries: { runMode: 3, openMode: 3 }, supportFile: '****', specPattern: '***/integration/**/*.cy.[tj]s', fixturesFolder: '***\src\\fixtures', screenshotsFolder: '***\\src\\screenshots', videosFolder: '***src\\videos', projectId: 'JKrQ64', video: true, viewportWidth: 1280, viewportHeight: 800, projectRoot: 'C:\\a\\3\\s\\Front', projectName: 'Front', isTextTerminal: true, trashAssetsBeforeRuns: false, animationDistanceThreshold: 5, arch: 'x64', blockHosts: null, chromeWebSecurity: true, clientCertificates: [], defaultCommandTimeout: 4000, downloadsFolder: 'C:\\a\\3\\s\\Front\\cypress\\downloads', execTimeout: 60000, experimentalCspAllowList: false, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalRunAllSpecs: false, experimentalMemoryManagement: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSkipDomainInjection: null, experimentalOriginDependencies: false, experimentalSourceRewriting: false, experimentalSingleTabRunMode: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: 'C:\\a\\3\\s\\Front', excludeSpecPattern: '*.hot-update.js', includeShadowDom: false, keystrokeDelay: 0, modifyObstructiveCode: true, numTestsKeptInMemory: 0, platform: 'win32', pageLoadTimeout: 60000, port: 58842, redirectionLimit: 20, reporter: 'spec', reporterOptions: null, requestTimeout: 5000, resolvedNodePath: 'C:\\hostedtoolcache\\windows\\node\\16.20.1\\x64\\node.exe', resolvedNodeVersion: '16.20.1', responseTimeout: 30000, screenshotOnRunFailure: true, slowTestThreshold: 10000, scrollBehavior: 'top', taskTimeout: 60000, testIsolation: true, userAgent: null, videoCompression: false, waitForAnimations: true, watchForFileChanges: false, browsers: [ [Object], [Object], [Object], [Object] ], cypressBinaryRoot: 'C:\\Users\\AzDevOps\\AppData\\Local\\Cypress\\Cache\\13.3.0\\Cypress\\resources\\app', hosts: null, isInteractive: true, version: '13.3.0', browser: null, cypressInternalEnv: 'production' }, cypressVersion: '13.3.0', endedTestsAt: '2023-10-10T13:26:45.228Z', osName: 'win32', osVersion: '10.0.20348', runs: [ { error: null, reporter: 'spec', reporterStats: [Object], screenshots: [], spec: [Object], stats: [Object], tests: [Array], video: '***' } ], startedTestsAt: '2023-10-10T13:26:00.198Z', totalDuration: 45030, totalFailed: 0, totalPassed: 16, totalPending: 0, totalSkipped: 0, totalSuites: 1, totalTests: 16 }
2023-10-10T13:26:46.530Z currents:state Instance "******" already has output
2023-10-10T13:26:46.530Z currents:capture resetting captured stdout
2023-10-10T13:26:46.530Z currents:reportTask Report task already created for instance ****
2023-10-10T13:26:46.530Z currents:runner Getting batched tasks: 3
2023-10-10T13:26:46.531Z currents:api network request: { method: 'post', url: 'runs/*****/cy/instances', headers: { Accept: 'application/json, text/plain, */*', 'Content-Type': 'application/json', 'x-cypress-request-attempt': 0, 'x-cypress-version': '13.3.0', 'x-ccy-version': '1.9.6', 'User-Agent': 'cypress-cloud/1.9.6', 'x-cypress-run-id': '****' }, data: { runId: '*', groupId: '****', machineId: '*****', platform: { osName: 'win32', osVersion: '10.0.20348', osCpus: [Array], osMemory: [Object], browserName: 'Electron', browserVersion: '114.0.5735.289' }, batchSize: 3 } }

  Reporting results and artifacts in background...  

2023-10-10T13:26:46.832Z currents:api network response: { status: 200, statusText: 'OK', headers: Object [AxiosHeaders] { date: 'Tue, 10 Oct 2023 13:26:46 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '639', connection: 'close', etag: '*****', 'apigw-requestid': '****=' }, data: { stdoutUploadUrl: 'https://fs.currents.dev/****', videoUploadUrl: null, screenshotUploadUrls: [], videoAssets: [], playwrightTraceUrls: null, coverageUploadUrl: null, cloud: { shouldCancel: false } } }
2023-10-10T13:26:46.832Z currents:results instance ***** artifact upload instructions { videoUploadUrl: null, screenshotUploadUrls: [], coverageUploadUrl: null }
2023-10-10T13:26:46.833Z currents:artifacts uploading artifacts: { videoPath: '*****src\\videos\\credit_actions.cy.ts.mp4', videoUploadUrl: null, screenshots: [], screenshotUploadUrls: [], coverageFilePath: undefined, coverageUploadUrl: null }
2023-10-10T13:26:46.834Z currents:api network request: { method: 'put', url: 'instances/*******/stdout', headers: { Accept: 'application/json, text/plain, */*', 'Content-Type': 'application/json', 'x-cypress-request-attempt': 0, 'x-cypress-version': '13.3.0', 'x-ccy-version': '1.9.6', 'User-Agent': 'cypress-cloud/1.9.6', 'x-cypress-run-id': '******' }, data: { stdout: "Using config file: 'file://*****\\currents.config.js'\n" + 'Discovered 1 spec files\n' + 'Tags: req; Group: false; Parallel: true; Batch Size: 3\n' + 'Connecting to cloud orchestration service...\n' + '🎥 Run URL: https://app.currents.dev/run/******\n' + '\n' + '====================================================================================================\n' + '\n' + 'Running: ******.cy.ts (1/1)\n' + '\r\n' + '\n' + '====================================================================================================\n' + '\n' + '  (Run Starting)\n' + '\n' + '  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐\n' + '  │ Cypress:        13.3.0                                                                         │\n' + '  │ Browser:        Electron 114 (headless)                                                        │\n' + '  │ Node Version:   v16.20.1 (C:\\hostedtoolcache\\windows\\node\\16.20.1\\x64\\node.exe)                │\n' + '  │ Specs:          1 found (****.cy.ts)                                                 │\n' + '  │ Searched:       ***** │\n' + '  │                 ***.cy.ts                                                                       │\n' + '  └────────────────────────────────────────────────────────────────────────────────────────────────┘\n' + '\n' + '\n' + '────────────────────────────────────────────────────────────────────────────────────────────────────\n' + '                                                                                                    \n' + '  Running:  ****.cy.ts                                                            (1 of 1)\n' + '\n' + '\n' + '  *****' } }
2023-10-10T13:26:46.908Z currents:api network response: { status: 200, statusText: 'OK', headers: Object [AxiosHeaders] { date: 'Tue, 10 Oct 2023 13:26:46 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '52', connection: 'close', etag: '****', 'apigw-requestid': '****=' }, data: { specs: [], claimedInstances: 1, totalInstances: 1 } }
2023-10-10T13:26:46.908Z currents:runner Got batched tasks: { specs: [], claimedInstances: 1, totalInstances: 1 }
2023-10-10T13:26:46.908Z currents:runner No more tasks to run. Uploads queue: 1

====================================================================================================

2023-10-10T13:26:47.114Z currents:api network response: { status: 200, statusText: 'OK', headers: Object [AxiosHeaders] { date: 'Tue, 10 Oct 2023 13:26:47 GMT', 'content-length': '0', connection: 'close', 'apigw-requestid': '****=' }, data: '' }

  Cloud Run Finished  

TypeError: Expected a finite number
    at prettyMS (C:\a\3\s\Front\node_modules\pretty-ms\index.js:10:9)
    at C:\a\3\s\Front\node_modules\lib\results\table.ts:25:10
    at Array.map (<anonymous>)
    at summaryTable (C:\a\3\s\Front\node_modules\lib\results\table.ts:22:23)
    at run (C:\a\3\s\Front\node_modules\lib\run.ts:147:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Command failed with exit code 1: npx cypress-cloud run --config-file ****/cypress.config.req.ts --cloud-config-file .****/currents.config.js --record --parallel --tag *** --ci-build-id **** --cloud-debug
    at makeError (C:\a\3\s\Front\node_modules\start-server-and-test\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\a\3\s\Front\node_modules\start-server-and-test\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: npx cypress-cloud run --config-file ***/cypress.config.req.ts --cloud-config-file ****/currents.config.js --record --parallel --tag req --ci-build-id *** --cloud-debug',
  command: 'npx cypress-cloud run --config-file ****/cypress.config.req.ts --cloud-config-file .****/currents.config.js --record --parallel --tag req --ci-build-id **** --cloud-debug',
  escapedCommand: '"npx cypress-cloud run --config-file ***/cypress.config.req.ts --cloud-config-file ****/currents.config.js --record --parallel --tag req --ci-build-id *** --cloud-debug"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
##[error]Cmd.exe exited with code '1'.



```

</details>

**Comment by agoldis** [comment]
@killergege please try the most recent `beta` channel - it should resolve the error. 
Also, please note that we provide [limited support](https://currents.dev/posts/v13-blocking) for Cypress because of their blocking of 3rd party libraries

**Comment by killergege** [comment]
Oh yes my bad, I didn't notice that we moved back a version instead of forward...
Sorry.

**Comment by darena-patrick** [comment]
> I'm facing the same error and can't find a solution... Could the problem be that I'm using cucumber-preprocessor and haven't configured setupNodeEvents correctly?
> 
> "cypress": "13.7.3", "cypress-cloud": "^1.10.2"
> 
> ```
> async function setupNodeEvents(
>   on:,
>   config:,
> ): {
>   await addCucumberPreprocessorPlugin(on, config)
> 
>   on(
>     "file:preprocessor",
>     createBundler({
>       plugins: [createEsbuildPlugin(config)],
>     }),
>   )
> 
>   return await cloudPlugin(on, config)
> }
> ```

Did you find a solution? Same deal here
