### ISSUE TITLE
Error:  Npx cypress-cloud  error

### ISSUE THREAD

**Issue by starkoff** [currents-dev/cypress-cloud#85]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz
    Memory: 4.91 GB / 9.99 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.41)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @cypress/angular:  0.0.0-development
    @cypress/mount-utils:  0.0.0-development
    @cypress/react:  0.0.0-development
    @cypress/react18:  0.0.0-development
    @cypress/svelte:  0.0.0-development
    @cypress/vue:  0.0.0-development
    @cypress/vue2:  0.0.0-development
    cypress: ^12.6.0 => 12.6.0
    cypress-cloud: ^1.4.4 => 1.4.4
    cypress-terminal-report: ^5.0.0 => 5.0.0
    ts-node: ^10.9.1 => 10.9.1


```

</details>

### Describe the bug

I run  test cypress-cloud  with connected to sorry-cypress server and the test didn't run. The sorry-cypress server is configured correctly and cy2 works correctly. attempts to configure with the help of the cypress-cloud package have not yet worked out for me

### Expected behavior

Run  clear example my test

### Command and Setup

default  docker-compose  sorry-cypress in linux server

use yml with cahnged passwords
https://github.com/sorry-cypress/sorry-cypress/blob/master/docker-compose.minio.yml

### Full log and debug output

<details>

```
// Put your logs below this line
 C:\work\nstarkov\first>npx cypress-cloud --parallel --record --key somekey --ci-build-id hello-cypress-cloud
  cypress:cli exporting Cypress module interface +0ms
  currents:cli parsed CLI flags { component: false, e2e: true, parallel: true, record: true, key: 'somekey', ciBuildId: 'hello-cypress-cloud' } +0ms
  currents:config loading currents config file from 'C:\work\nstarkov\first\currents.config.js' +0ms
  currents:capture capturing stdout +0ms
  currents:cli parsed run params: { parallel: true, record: true, key: 'somekey', ciBuildId: 'hello-cypress-cloud', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', projectId: 'dev2cloud', batchSize: 3 } +93ms

  currents:index run api params { parallel: true, record: true, key: 'somekey', ciBuildId: 'hello-cypress-cloud', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', projectId: 'dev2cloud', batchSize: 3 } +0ms
  currents:config resolving cypress config  +148ms
  currents:boot booting cypress... +0ms
  currents:boot booting cypress with args: [ 'run', '--spec', 'ppdzmvxbjo', '--env', '{"currents_temp_file":"C:\\\\Users\\\\jenkins\\\\AppData\\\\Local\\\\Temp\\\\tmp-7988-d4FFwrL3yWpb","currents_port":58449,"currents_debug_enabled":"true"}', '--e2e' ] +60ms
  currents:boot cypress executable location: C:\work\nstarkov\first\node_modules\cypress\bin\cypress +9ms
  currents:boot read config temp file failed: Error: Is cypress-cloud/plugin installed? at bootCypress (C:\work\nstarkov\first\node_modules\lib\bootstrap.ts:70:13) at getConfig (C:\work\nstarkov\first\node_modules\lib\config.ts:65:19) at run (C:\work\nstarkov\first\node_modules\index.ts:45:18) +9ms

====================================================================================================

 ERROR  TypeError: Cannot read properties of null (reading 'toString')
    at bootCypress (C:\work\nstarkov\first\node_modules\lib\bootstrap.ts:76:46)
    at getConfig (C:\work\nstarkov\first\node_modules\lib\config.ts:65:19)
    at run (C:\work\nstarkov\first\node_modules\index.ts:45:18)

C:\work\nstarkov\first>
```

</details>
![screenshot](https://user-images.githubusercontent.com/2722116/225479319-896aa6d6-b5d9-42b5-b740-102f0ecdf594.png)

**Comment by agoldis** [comment]
I've published 1.4.5-beta.0 on npm - please confirm it's working for you
