### ISSUE TITLE
Error 400 from sorry-cypress since updating from 1.4.4 to 1.4.5-beta.0 or 1.5.0

### ISSUE THREAD

**Issue by mirobo** [currents-dev/cypress-cloud#96]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   
    Memory: 8.29 GB / 31.74 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD 
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.41)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @cypress/angular:  0.0.0-development 
    @cypress/mount-utils:  0.0.0-development 
    @cypress/react:  0.0.0-development 
    @cypress/react18:  0.0.0-development 
    @cypress/svelte:  0.0.0-development 
    @cypress/vue:  0.0.0-development 
    @cypress/vue2:  0.0.0-development 
    cypress: ^12.7.0 => 12.7.0 
    cypress-cloud: 1.5.0 => 1.5.0 
  npmGlobalPackages:
    corepack: 0.15.2
    npm: 8.19.3
    rimraf: 4.1.2
```

</details>

### Describe the bug

Since **upgrading from 1.4.4** to 1.4.5-beta0 (and 1.5.0) the plugin itself can no longer communicate with sorry-cypress (error 400).

I tested it twice, with two instance of sorry-cypress (one with version 2.5.3 and one with 2.1.3). They both responded with error "400". I guess it's purely a client side error but it's suboptimal that the Module API version just returns an undefined object rather than some kind of error message details like with the command "npx cypress-cloud".

### Expected behavior

Communcation works as in 1.4.4

### Command and Setup

Error from "./run-tests-ci.**sh**" command (this worked in 1.4.4):
```
 ERROR  Error: Request failed with status code 400
    at C:\views\_\cypress-cloud-module-api\node_modules\lib\httpClient\httpClient.ts:92:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createRun (C:\views\_\cypress-cloud-module-api\node_modules\lib\api\api.ts:17:20)
    at run (C:\views\_\cypress-cloud-module-api\node_modules\index.ts:70:15)
```

Error from "node run-tests-ci.js" command:

```
...
const result = await run({
    ciBuildId: getCiBuildId(),
  }).catch((err) => {
    console.error(`error occurred`);
    console.error(JSON.stringify(err, null, 2));
    exitCode = 999;
  });
...
```
produced output:

```
error occurred
{}
Result object from cypress-cloud run command:
undefined
```

### Full log and debug output

Full logs and used scripts are here:

https://github.com/mirobo/cypress-cloud-module-api/blob/main/run-tests-ci.sh
https://github.com/mirobo/cypress-cloud-module-api/blob/main/log-sh.txt

https://github.com/mirobo/cypress-cloud-module-api/blob/main/run-tests-ci.js
https://github.com/mirobo/cypress-cloud-module-api/blob/main/log-js.txt

**Comment by agoldis** [comment]
@mirobo I have just tried sending your payload to local instance of sorry-cypress - it's working fine. 

```
curl --location 'http://localhost:1235/runs' \
--header 'Content-Type: application/json' \
--data '{
    "ci": {
        "params": {},
        "provider": null
    },
    "specs": [
        "cypress\\e2e\\1-getting-started\\todo.cy.js"
    ],
    "commit": {
        "branch": "main",
        "remoteOrigin": "",
        "authorEmail": "mirobo",
        "authorName": "mirobo",
        "message": "update cypress-cloud to 1.4.5-beta.0\n",
        "sha": "0c3a4449fe09f6d6c58fa3f3e5a3630aea68d6d5"
    },
    "platform": {
        "osName": "win32",
        "osVersion": "10.0.19044",
        "browserName": "Electron",
        "browserVersion": "106.0.5249.51"
    },
    "parallel": true,
    "ciBuildId": "2023-03-16T12: 17: 33.582Z",
    "projectId": "test",
    "recordKey": "cccc",
    "specPattern": [
        "cypress/e2e /**/*.cy.{js,jsx,ts,tsx}"
    ],
    "testingType": "e2e",
    "batchSize": 3
}'
```

**Comment by mirobo** [comment]
After the log `currents:api network request: ` I see this:

```
follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: Infinity,
  protocol: 'http:',
  path: 'https://some-sorry-cypress-director/runs',
  method: 'POST',
  headers: [Object: null prototype] {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    'x-cypress-request-attempt': '0',
    'x-cypress-version': '12.6.0',
    'x-ccy-version': '1.5.0',
    'User-Agent': 'axios/1.3.4',
    'Content-Length': '2596',
    'Accept-Encoding': 'gzip, compress, deflate, br',
    host: 'some-sorry-cypress-director'
  },
  agents: { http: undefined, https: undefined },
  auth: undefined,
  beforeRedirect: [Function: dispatchBeforeRedirect],
  beforeRedirects: { proxy: [Function: beforeRedirect] },
  hostname: 'localhost',
  port: '3128',
  host: 'localhost',
  agent: undefined,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function: __node_internal_],
      validateHeaderValue: [Function: __node_internal_],
      get: [Function: get],
      request: [Function: request],
      setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +0ms
```

I also just tried with cURL and it works, but I needed to add "--insecure" flag.

```
curl --location 'https://some-sorry-cypress-director/runs' \
--header 'Content-Type: application/json' \
--insecure \
--data '{
    "ci": {
        "params": {},
        "provider": null
    },
    "specs": [
        "cypress\\e2e\\1-getting-started\\todo.cy.js"
    ],
    "commit": {
        "branch": "main",
        "remoteOrigin": "",
        "authorEmail": "mirobo",
        "authorName": "mirobo",
        "message": "update cypress-cloud to 1.4.5-beta.0\n",
        "sha": "0c3a4449fe09f6d6c58fa3f3e5a3630aea68d6d5"
    },
    "platform": {
        "osName": "win32",
        "osVersion": "10.0.19044",
        "browserName": "Electron",
        "browserVersion": "106.0.5249.51"
    },
    "parallel": true,
    "ciBuildId": "2023-03-16T12: 17: 33.582Z",
    "projectId": "fipo2/system-test",
    "recordKey": "cccc",
    "specPattern": [
        "cypress/e2e /**/*.cy.{js,jsx,ts,tsx}"
    ],
    "testingType": "e2e",
    "batchSize": 3
}'
```

Response
```
{
"groupId":"2023-03-16T12: 17: 33.582Z",
"machineId":"f34012d9-8b8f-46f3-8922-3c98ed81b866",
"runId":"dccee29bca5cba898f715e64e3c3eb04",
"runUrl":"https://some-sorry-cypress-dashboard/run/dccee29bca5cba898f715e64e3c3eb04",
"isNewRun":true,
"warnings":[]
}
```

I guess this is an axios-specific issue? I'll try to execute the request in pure axios to see what happens..

**Comment by mirobo** [comment]
@agoldis "proxy-from-env" used in "axios" ( https://github.com/Rob--W/proxy-from-env/blob/master/index.js#L62 ) interprets NO_PROXY differently compared to NPM ( https://github.com/npm/make-fetch-happen/blob/main/lib/agent.js#L93 ) 😤😭🤡. 

All I needed was a dot in front of my domain that should not be proxied. Don't ask me why it worked once before locally.. maybe I was just dreaming..

When I used the normal "https" library from Node, it interpreted the NO_PROXY env variable as expected and I could normally do a POST request on the director. All I can say now is: Arghhhhxios.. 🤡
